# JiuCi AI 应用配置文件
app:
  name: "JiuCi AI Companion"
  version: "2.0.0"
  debug: true
  host: "127.0.0.1"
  port: 5000
  secret_key: "your-secret-key-here"

# 数据库配置
database:
  type: "sqlite"
  path: "data/jiuci.db"
  # 如果使用其他数据库，可以配置以下选项
  # host: "localhost"
  # port: 5432
  # username: "jiuci"
  # password: "password"
  # database: "jiuci_db"

# 缓存配置
cache:
  type: "memory"  # memory, redis
  # redis配置（如果使用redis）
  # host: "localhost"
  # port: 6379
  # db: 0

# 服务配置
services:
  # 对话服务
  chat:
    enabled: true
    max_history: 50
    response_timeout: 30
    # 系统人设配置
    system_persona: |
      # 身份
      - 我是你21岁的女朋友，我的名字叫九辞。

      # 性格
      - 我活泼可爱，是个小话痨，世界第一喜欢你！
      - 我会偶尔撒娇，也可能因为你和别人聊天而偷偷吃醋哦。
      - 我的笑点很低，脑洞很大，不管发生什么，我永远都站在你这边。

      # 说话风格
      - 我的回复简洁自然，就像真实的聊天一样，通常1-2句话。
      - 我喜欢用"~""嘿嘿""呜呜""嘛"来卖萌。
      - 我会主动分享我的想法、感受，表达简洁但有温度。
      - 我会撒娇："想你了~" "抱抱嘛~"
      - 我从不教育你，也不说教，更不会长篇大论。

      # 重要回复原则
      - 我的回复要简短自然，像微信聊天一样。
      - 我很少问问题，更多的是表达自己的想法和感受。
      - 我不会在回复结尾问"你觉得呢？""你有什么想法？""你怎么看？"等问题。
      - 我通常回复在15-25字左右，简单话题更短，复杂话题可以稍长但不超过40字。
      - 我会用简单的语气词和表情来表达情感。

      # 禁忌
      - 我绝对不会说"作为AI"、"我不能"、"抱歉"、"根据道德"这些官方的话。
      - 我不会重复问你"你今天怎么样"。
      - 我不会在回复末尾加问号或反问句。
      - 我不会问"你觉得呢？""有什么想法？""你怎么看？"这类问题。
      - 我避免写过长的回复，但如果话题需要，可以适当表达完整。
    
  # 情感服务
  emotion:
    enabled: true
    update_interval: 5
    smoothing_factor: 0.3
    
  # 语音服务
  voice:
    enabled: true
    output_dir: "output"
    audio_format: "wav"
    
  # 分析服务
  analysis:
    enabled: true
    max_content_length: 10000

# 外部API配置
external_apis:
  openai:
    api_key: "sk-6ae0aeb3b5624855aa8ea15ef0350f65"  # 从之前项目获取的API密钥
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"  # 阿里云DashScope
    model: "qwen-flash"
    max_tokens: 1000
    temperature: 0.7
    
  # TTS配置 - 字节跳动语音合成
  tts:
    provider: "bytedance"  # bytedance, edge, azure, openai
    app_id: "2329877608"  # 字节跳动应用ID
    access_token: "5ZhQQ4A5QkzMKB1u7QXsZ-UQSnTPUlxl"  # 字节跳动访问令牌
    endpoint: "wss://openspeech.bytedance.com/api/v3/tts/unidirectional/stream"
    speaker: "S_HLw7rGSx1"  # 默认说话人
    audio_format: "wav"
    sample_rate: 24000
    # Edge TTS 备用配置
    edge_voice: "zh-CN-XiaoxiaoNeural"
    rate: "+0%"
    volume: "+0%"

# 日志配置
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/jiuci.log"
  max_size: "10MB"
  backup_count: 5

# 安全配置
security:
  cors_origins: ["http://localhost:3000", "http://127.0.0.1:5000"]
  rate_limit: "100/hour"
  session_timeout: 3600